<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/08/30 17:32:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'z',
  'name' => 'doctrine',
)),);
