<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/30 17:32:37
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 4,
  'app_max_jobs_on_category' => 5,
));
