<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/25 17:11:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'zuzanna',
  'name' => 'doctrine',
)),);
